### ISSUE TITLE
android 端报错

### ISSUE THREAD

**Issue by VictorYuan666** [csvwolf/weex-vue-starter-kit#2]
工程下下来 npm install ，add android 后  运行打开报render error：null

**Comment by VictorYuan666** [comment]
已经知道了 是android端weex sdk 的版本不对 build.gradle里改成compile 'com.taobao.android:weex_sdk:0.9.5'

**Comment by csvwolf** [comment]
@VictorYuan666 你好，感谢你的 issue，能发一下完整的 build.gradle 么，能方便很多前端
