### ISSUE TITLE
about project name

### ISSUE THREAD

**Issue by xujingbao** [csvwolf/weex-vue-starter-kit#4]
weexpack platform add ios

gen a project named WeexDemo，How to change it？

**Comment by csvwolf** [comment]
Hello, if you are not familiar with iOS development, the simplest way is to use Xcode to open the generated ios project and read the article to edit display name:

<https://codesky.me/archives/xcode-compile-weex-playground-to-your-own-phone.wind>

And you can edit the project name in the sidebar: identity and type - name.

**Comment by xujingbao** [comment]
So default project name can not change in weexpack.

**Comment by csvwolf** [comment]
@xujingbao Yes, weexpack don't provide the feature, but you can edit it in Xcode by yourself. If you need the feature, you can post an issue to weexpack.
